version: '3'

services:
  redis:
    image: redis

  app:
    image: jaywink/the-federation.info:latest
    depends_on:
      - redis
    env_file:
      - .env

  web:
    image: jaywink/the-federation.info-web:latest
    depends_on:
      - app
    ports:
      - "127.0.0.1:8123:80"
