version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    volumes:
      - ./dbdata:/var/lib/postgresql/data

  redis:
    image: redis

  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    depends_on:
      - db
      - redis
    env_file:
      - .env

#  TODO replace with container running node http-server or something
#  web:
#    build:
#      context: .
#      dockerfile: docker/nginx/Dockerfile
#      args:
#        env: $TARGET_ENV
#    depends_on:
#      - app
#    ports:
#      - "127.0.0.1:8123:80"
